// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRNJ1jXf2LXL1Gf8wzmBndsmIiyMrfTDo',
    appId: '1:594908184850:web:27e809290b54a83229b3cb',
    messagingSenderId: '594908184850',
    projectId: 'campuscloset-8c8f5',
    authDomain: 'campuscloset-8c8f5.firebaseapp.com',
    storageBucket: 'campuscloset-8c8f5.firebasestorage.app',
    measurementId: 'G-9GX9QJKSZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPQHeyw6mAnv1qWdSoSt_P_5sQsEQHOCg',
    appId: '1:594908184850:android:4cd13c9a7271b6cb29b3cb',
    messagingSenderId: '594908184850',
    projectId: 'campuscloset-8c8f5',
    storageBucket: 'campuscloset-8c8f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXBghKFYMJzXe3qMKv5FcMhq5ga1qwR-Q',
    appId: '1:594908184850:ios:bc81334557f5a24c29b3cb',
    messagingSenderId: '594908184850',
    projectId: 'campuscloset-8c8f5',
    storageBucket: 'campuscloset-8c8f5.firebasestorage.app',
    iosBundleId: 'com.example.profileManagemenr',
  );
}
