import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';

import 'package:profile_managemenr/services/auth_service.dart';
import 'package:profile_managemenr/home/core/routes/app_routes.dart';
import 'package:profile_managemenr/home/core/widgets/auth_wrapper.dart';
import 'package:profile_managemenr/constants/app_theme.dart';
import 'firebase_options.dart'; // Generated by FlutterFire

void main() async {
  // Ensure Flutter framework is ready for async work
  WidgetsFlutterBinding.ensureInitialized();

  // Load environment variables from .env file
  await dotenv.load(fileName: ".env");

  // Initialize Firebase (required before runApp)
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    // Optional: log Firebase init errors
    debugPrint("Firebase initialization error: $e");
    rethrow;
  }

  // Run the app
  runApp(const MyApp());
}

/// Root widget that configures providers and MaterialApp
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        // Auth state management
        ChangeNotifierProvider(
          create: (_) => AuthService(),
        ),
        // Add more providers here if needed (e.g., ItemProvider, CartProvider)
      ],
      child: MaterialApp(
        title: 'Campus Closet',
        theme: AppTheme.lightTheme,
        darkTheme: AppTheme.darkTheme,
        themeMode: ThemeMode.light, // or ThemeMode.system
        debugShowCheckedModeBanner: false,
        home: const AuthWrapper(), // handles login vs home redirect
        routes: AppRoutes.routes,  // all named routes
        // Optional: fallback route for unknown paths
        onUnknownRoute: (settings) => MaterialPageRoute(
          builder: (_) => Scaffold(
            body: Center(
              child: Text('Page not found: ${settings.name}'),
            ),
          ),
        ),
      ),
    );
  }
}